#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Jul 08, 2024 04:09:39 AM CDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import calc1_support

_bgcolor = 'cornsilk3'
_fgcolor = 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: calc1_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'cornsilk-light.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('cornsilk-light')
    style.configure('.', font = "-family {DejaVu Sans} -size 10")
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("359x467+1220+654")
        top.minsize(1, 1)
        top.maxsize(4225, 1410)
        top.resizable(0,  0)
        top.title("Calc1")
        top.configure(background="cornsilk3")
        top.configure(highlightbackground="cornsilk3")
        top.configure(highlightcolor="black")

        self.top = top
        self.Display = tk.StringVar()

        _style_code()
        self.TButton1 = ttk.Button(self.top)
        self.TButton1.place(x=10, y=140, height=49, width=62)
        self.TButton1.configure(command=lambda :calc1_support.on_numKey(7))
        self.TButton1.configure(text='''7''')
        self.TButton1.configure(compound='left')

        self.TButton2 = ttk.Button(self.top)
        self.TButton2.place(x=75, y=140, height=49, width=62)
        self.TButton2.configure(command=lambda :calc1_support.on_numKey(8))
        self.TButton2.configure(text='''8''')
        self.TButton2.configure(compound='left')

        self.TButton3 = ttk.Button(self.top)
        self.TButton3.place(x=140, y=140, height=49, width=62)
        self.TButton3.configure(command=lambda :calc1_support.on_numKey(9))
        self.TButton3.configure(text='''9''')
        self.TButton3.configure(compound='left')

        self.TButton4 = ttk.Button(self.top)
        self.TButton4.place(x=10, y=191, height=49, width=62)
        self.TButton4.configure(command=lambda :calc1_support.on_numKey(4))
        self.TButton4.configure(text='''4''')
        self.TButton4.configure(compound='left')

        self.TButton5 = ttk.Button(self.top)
        self.TButton5.place(x=75, y=191, height=49, width=62)
        self.TButton5.configure(command=lambda :calc1_support.on_numKey(5))
        self.TButton5.configure(text='''5''')
        self.TButton5.configure(compound='left')

        self.TButton6 = ttk.Button(self.top)
        self.TButton6.place(x=140, y=190, height=49, width=62)
        self.TButton6.configure(command=lambda :calc1_support.on_numKey(6))
        self.TButton6.configure(text='''6''')
        self.TButton6.configure(compound='left')

        self.TButton7 = ttk.Button(self.top)
        self.TButton7.place(x=10, y=242, height=49, width=62)
        self.TButton7.configure(command=lambda :calc1_support.on_numKey(1))
        self.TButton7.configure(text='''1''')
        self.TButton7.configure(compound='left')

        self.TButton8 = ttk.Button(self.top)
        self.TButton8.place(x=75, y=242, height=49, width=62)
        self.TButton8.configure(command=lambda :calc1_support.on_numKey(2))
        self.TButton8.configure(text='''2''')
        self.TButton8.configure(compound='left')

        self.TButton12 = ttk.Button(self.top)
        self.TButton12.place(x=220, y=140, height=49, width=62)
        self.TButton12.configure(command=lambda :calc1_support.on_funcKey('Divide'))
        self.TButton12.configure(text='''÷''')
        self.TButton12.configure(compound='left')

        self.TButton13 = ttk.Button(self.top)
        self.TButton13.place(x=220, y=191, height=49, width=62)
        self.TButton13.configure(command=lambda :calc1_support.on_funcKey('Mult'))
        self.TButton13.configure(text='''x''')
        self.TButton13.configure(compound='left')

        self.TButton14 = ttk.Button(self.top)
        self.TButton14.place(x=220, y=242, height=49, width=62)
        self.TButton14.configure(command=lambda :calc1_support.on_funcKey('Sub'))
        self.TButton14.configure(text='''-''')
        self.TButton14.configure(compound='left')

        self.TButton15 = ttk.Button(self.top)
        self.TButton15.place(x=220, y=293, height=49, width=62)
        self.TButton15.configure(command=lambda :calc1_support.on_funcKey('Add'))
        self.TButton15.configure(text='''+''')
        self.TButton15.configure(compound='left')

        self.TButton16 = ttk.Button(self.top)
        self.TButton16.place(x=287, y=240, height=102, width=62)
        self.TButton16.configure(command=lambda :calc1_support.on_funcKey('Equal'))
        self.TButton16.configure(text='''=''')
        self.TButton16.configure(compound='left')

        self.TButton17 = ttk.Button(self.top)
        self.TButton17.place(x=290, y=140, height=48, width=59)
        self.TButton17.configure(command=lambda :calc1_support.on_funcKey('Clear'))
        self.TButton17.configure(text='''⌫''')
        self.TButton17.configure(compound='left')

        self.TButton10 = ttk.Button(self.top)
        self.TButton10.place(x=10, y=293, height=49, width=127)
        self.TButton10.configure(command=lambda :calc1_support.on_numKey(0))
        self.TButton10.configure(text='''0''')
        self.TButton10.configure(compound='left')

        self.TButton9 = ttk.Button(self.top)
        self.TButton9.place(x=140, y=242, height=49, width=62)
        self.TButton9.configure(command=lambda :calc1_support.on_numKey(3))
        self.TButton9.configure(text='''3''')
        self.TButton9.configure(compound='left')

        self.TButton11 = ttk.Button(self.top)
        self.TButton11.place(x=140, y=293, height=49, width=62)
        self.TButton11.configure(command=lambda :calc1_support.on_numKey('.'))
        self.TButton11.configure(text='''.''')
        self.TButton11.configure(compound='left')

        self.TLabel1 = ttk.Label(self.top)
        self.TLabel1.place(x=2, y=60, height=50, width=355)
        self.TLabel1.configure(background="white")
        self.TLabel1.configure(font="-family {DejaVu Sans} -size 20 -weight bold")
        self.TLabel1.configure(relief="sunken")
        self.TLabel1.configure(anchor='w')
        self.TLabel1.configure(justify='left')
        self.TLabel1.configure(text='''Tlabel''')
        self.TLabel1.configure(textvariable=self.Display)
        self.Display.set('''Tlabel''')
        self.TLabel1.configure(compound='left')

def start_up():
    calc1_support.main()

if __name__ == '__main__':
    calc1_support.main()




