#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Jul 08, 2024 04:09:39 AM CDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_dft_desc) $desc
set vTcl(actual_gui_font_dft_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
set vTcl(project_theme) cornsilk-light



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background cornsilk3 -highlightbackground cornsilk3 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 359x467+1220+654
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4225 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Calc1"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::button "$top.tBu47" \
        -command "lambda : on_numKey(7)" -text "7" -compound left 
    vTcl:DefineAlias "$top.tBu47" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu48" \
        -command "lambda : on_numKey(8)" -text "8" -compound left 
    vTcl:DefineAlias "$top.tBu48" "TButton2" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu49" \
        -command "lambda : on_numKey(9)" -text "9" -compound left 
    vTcl:DefineAlias "$top.tBu49" "TButton3" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu51" \
        -command "lambda : on_numKey(4)" -text "4" -compound left 
    vTcl:DefineAlias "$top.tBu51" "TButton4" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu52" \
        -command "lambda : on_numKey(5)" -text "5" -compound left 
    vTcl:DefineAlias "$top.tBu52" "TButton5" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu53" \
        -command "lambda : on_numKey(6)" -text "6" -compound left 
    vTcl:DefineAlias "$top.tBu53" "TButton6" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu54" \
        -command "lambda : on_numKey(1)" -text "1" -compound left 
    vTcl:DefineAlias "$top.tBu54" "TButton7" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu56" \
        -command "lambda : on_numKey(2)" -text "2" -compound left 
    vTcl:DefineAlias "$top.tBu56" "TButton8" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu60" \
        -command "lambda : on_funcKey('Divide')" -text "÷" -compound left 
    vTcl:DefineAlias "$top.tBu60" "TButton12" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu61" \
        -command "lambda : on_funcKey('Mult')" -text "x" -compound left 
    vTcl:DefineAlias "$top.tBu61" "TButton13" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu62" \
        -command "lambda : on_funcKey('Sub')" -text "-" -compound left 
    vTcl:DefineAlias "$top.tBu62" "TButton14" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu63" \
        -command "lambda : on_funcKey('Add')" -text "+" -compound left 
    vTcl:DefineAlias "$top.tBu63" "TButton15" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu64" \
        -command "lambda : on_funcKey('Equal')" -text "=" -compound left 
    vTcl:DefineAlias "$top.tBu64" "TButton16" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu50" \
        -command "lambda : on_funcKey('Clear')" -text "⌫" -compound left 
    vTcl:DefineAlias "$top.tBu50" "TButton17" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu55" \
        -command "lambda : on_numKey(0)" -text "0" -compound left 
    vTcl:DefineAlias "$top.tBu55" "TButton10" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu57" \
        -command "lambda : on_numKey(3)" -text "3" -compound left 
    vTcl:DefineAlias "$top.tBu57" "TButton9" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu59" \
        -command "lambda : on_numKey('.')" -text "." -compound left 
    vTcl:DefineAlias "$top.tBu59" "TButton11" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$top.tLa50" \
        -background white -font "-family {DejaVu Sans} -size 20 -weight bold" \
        -relief sunken -anchor w -justify left -text "Tlabel" \
        -textvariable "::Display" -compound left 
    vTcl:DefineAlias "$top.tLa50" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    set ::Display {Tlabel}
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tBu47 \
        -in $top -x 10 -y 140 -width 62 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu48 \
        -in $top -x 75 -y 140 -width 62 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu49 \
        -in $top -x 140 -y 140 -width 62 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu51 \
        -in $top -x 10 -y 191 -width 62 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu52 \
        -in $top -x 75 -y 191 -width 62 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu53 \
        -in $top -x 140 -y 190 -width 62 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu54 \
        -in $top -x 10 -y 242 -width 62 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu56 \
        -in $top -x 75 -y 242 -width 62 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu60 \
        -in $top -x 220 -y 140 -width 62 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu61 \
        -in $top -x 220 -y 191 -width 62 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu62 \
        -in $top -x 220 -y 242 -width 62 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu63 \
        -in $top -x 220 -y 293 -width 62 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu64 \
        -in $top -x 287 -y 240 -width 62 -relwidth 0 -height 102 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu50 \
        -in $top -x 290 -y 140 -width 59 -relwidth 0 -height 48 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu55 \
        -in $top -x 10 -y 293 -width 127 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu57 \
        -in $top -x 140 -y 242 -width 62 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu59 \
        -in $top -x 140 -y 293 -width 62 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa50 \
        -in $top -x 2 -y 60 -width 355 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

